POST http://localhost:3000/user/reviews/set/add
Content-Type: application/json

{
    "user":"5e97f7e4ed90401a58eca3ea",
    "id":"5eaba956713d0b1eac4643f2",
    "day":"tuesday",
    "review":{
        "timestamp":"26/02/2020",
        "timeTaken":12435343,
        "technique":10,
        "rating":6
    }
}